export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_OUT: 'LOGIN_OUT',
    RESGISTER_TEMP: 'RESGISTER_TEMP',
    RESGISTER_SUCCESS: 'RESGISTER_SUCCESS',
    GAMELIST_SUCCESS: 'GAMELIST_SUCCESS'
}; 